---
apiVersion: v1
kind: Pod
metadata:
  name: demo.limit
spec:
  containers:
  - name: abc
    image: nginx
    resources:
      limits:
        cpu: "1"

---
apiVersion: v1
kind: Pod
metadata:
  name: demo.request
spec:
  containers:
  - name: xyz
    image: nginx
    resources:
      requests:
        cpu: "0.75"
        

---
apiVersion: v1
kind: Pod
metadata:
  name: memory.demo
spec:
  containers:
  - name: cont.memory
    image: nginx
    resources:
      limits:
        memory: "800Mi"
      requests:
        memory: "600Mi"
